"""Turn validated domain + technical knowledge into a Prolog program.

Prolog reads uppercase words as variables, so entity names are written in
lowercase snake form (Book -> book, BookAuthor -> book_author). `NameMap`
maps them back for messages.

Every bridge rule becomes Prolog clauses whose last argument is the rule id,
so each derived decision carries its own proof.
"""

import re
from collections import defaultdict
from importlib import resources

from harness.knowledge.schema import Condition, Domain, Outcome, Technical

LIBRARY = ("core.pl", "checks.pl")

# Fact and decision predicates; declared dynamic so a query never fails with
# "unknown procedure" when a project happens to have no facts of that kind.
FACTS = [
    "area/1",
    "entity/2",
    "identifier/2",
    "attribute/3",
    "required/2",
    "unique/2",
    "generated/2",
    "lifecycle/3",
    "transition_allowed/3",
    "association/5",
    "service/1",
    "kind/2",
    "acts_on/2",
    "uses/2",
    "within/2",
    "filter/2",
    "changes/2",
    "moves/3",
    "kind_method/2",
    "kind_persistence/2",
    "kind_status/2",
    "kind_target/2",
    "component_known/1",
    "askable/1",
    "fact/2",
    "flow_start/1",
    "flow_step/1",
    "flow_outcome/1",
    "flow_edge/2",
]
DECISIONS = [
    "component/3",
    "error_status/3",
    "route/3",
    "route_param/3",
    "query_params/3",
    "response_includes/3",
    "persistence_target/3",
]

# once(...) asks *whether* there is a match, so a rule fires once per service
# even when the service has several filters, changes, etc.
HAS = {
    "filters": "once(filter(S, _))",
    "changes": "once(changes(S, _))",
    "moves": "once(moves(S, _, _))",
    "within": "once(within(S, _))",
    "association": "once(uses(S, _))",
}


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def atom(text: str) -> str:
    """A Prolog atom: bare when it is a plain lowercase word, quoted otherwise."""
    if re.fullmatch(r"[a-z][a-zA-Z0-9_]*", text):
        return text
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


class NameMap:
    """Prolog atoms back to the names used in the YAML."""

    def __init__(self, domain: Domain):
        self._entities = {snake(name): name for name in domain.entities}

    def entity(self, atom_name: str) -> str:
        return self._entities.get(atom_name, atom_name)


class Program:
    """Clauses collected per predicate, so each predicate's clauses stay together."""

    def __init__(self) -> None:
        self._clauses: dict[str, list[str]] = defaultdict(list)

    def add(self, predicate: str, clause: str, comment: str | None = None) -> None:
        if comment:
            self._clauses[predicate].append(f"% {comment}")
        self._clauses[predicate].append(clause)

    def render(self) -> str:
        parts = []
        for predicate, clauses in self._clauses.items():
            parts.append(f"% ── {predicate} " + "─" * max(0, 60 - len(predicate)))
            parts.extend(clauses)
            parts.append("")
        return "\n".join(parts)


def compile_knowledge(domain: Domain, technical: Technical) -> str:
    program = Program()
    _domain_facts(program, domain)
    _technical_facts(program, technical)
    _bridge_rules(program, technical)
    header = [
        "% Generated by `harness` from domain.yaml and technical.yaml. Do not edit by hand.",
        "% Entity names are lowercase here (Book -> book): in Prolog, uppercase means variable.",
        "",
        f":- dynamic {', '.join(FACTS + DECISIONS)}.",
        "",
    ]
    return "\n".join(header) + program.render()


def library() -> str:
    """The fixed Prolog that ships with the harness: core decisions and logic checks."""
    folder = resources.files("harness.logic")
    return "\n".join((folder / name).read_text() for name in LIBRARY)


def _domain_facts(p: Program, domain: Domain) -> None:
    for name in domain.areas:
        p.add("area/1", f"area({atom(name)}).")
    for name, entity in domain.entities.items():
        e = atom(snake(name))
        p.add("entity/2", f"entity({e}, {atom(entity.area)}).")
        p.add("identifier/2", f"identifier({e}, {atom(entity.identifier)}).")
        for attr, spec in entity.attributes.items():
            a = atom(attr)
            p.add("attribute/3", f"attribute({e}, {a}, {atom(spec.type)}).")
            for flag in ("required", "unique", "generated"):
                if getattr(spec, flag):
                    p.add(f"{flag}/2", f"{flag}({e}, {a}).")
        if entity.lifecycle:
            lc = entity.lifecycle
            p.add("lifecycle/3", f"lifecycle({e}, {atom(lc.field)}, {atom(lc.initial)}).")
            for t in lc.transitions:
                p.add(
                    "transition_allowed/3",
                    f"transition_allowed({e}, {atom(t.from_)}, {atom(t.to)}).",
                )
    for name, a in domain.associations.items():
        p.add(
            "association/5",
            f"association({atom(name)}, {a.kind}, {atom(snake(a.parent))}, "
            f"{atom(snake(a.child))}, {a.cardinality}).",
        )
    for name, s in domain.services.items():
        sv = atom(name)
        p.add("service/1", f"service({sv}).")
        p.add("kind/2", f"kind({sv}, {atom(s.kind)}).")
        if s.acts_on:
            p.add("acts_on/2", f"acts_on({sv}, {atom(snake(s.acts_on))}).")
        if s.association:
            p.add("uses/2", f"uses({sv}, {atom(s.association)}).")
        if s.within:
            p.add("within/2", f"within({sv}, {atom(snake(s.within))}).")
        for f in s.filters:
            p.add("filter/2", f"filter({sv}, {atom(f)}).")
        for c in s.changes:
            p.add("changes/2", f"changes({sv}, {atom(c)}).")
        if s.moves:
            p.add("moves/3", f"moves({sv}, {atom(s.moves.from_)}, {atom(s.moves.to)}).")


def _technical_facts(p: Program, technical: Technical) -> None:
    for name, kind in technical.kinds.items():
        k = atom(name)
        p.add("kind_method/2", f"kind_method({k}, {kind.method.lower()}).")
        p.add("kind_persistence/2", f"kind_persistence({k}, {atom(kind.persistence)}).")
        p.add("kind_status/2", f"kind_status({k}, {kind.status}).")
        p.add("kind_target/2", f"kind_target({k}, {kind.target}).")
    for name in technical.components:
        p.add("component_known/1", f"component_known({atom(name)}).")
    for name in technical.askable:
        p.add("askable/1", f"askable({atom(name)}).")

    flow = technical.classification
    p.add("flow_start/1", f"flow_start({atom(flow.start)}).")
    for outcome in flow.outcomes:
        p.add("flow_outcome/1", f"flow_outcome({atom(outcome)}).")
    for name, step in flow.steps.items():
        s = atom(name)
        p.add("flow_step/1", f"flow_step({s}).")
        answers = (
            [step.on_answer]
            if isinstance(step.on_answer, str)
            else list(step.on_answer.cases.values())
        )
        for target in dict.fromkeys([*answers, step.on_none, flow.low_confidence]):
            p.add("flow_edge/2", f"flow_edge({s}, {atom(target)}).")


def _bridge_rules(p: Program, technical: Technical) -> None:
    for rule in technical.rules:
        body = ", ".join(_conditions(rule.when))
        rid = atom(rule.id)
        for predicate, head in _outcomes(rule.then, rid):
            p.add(predicate, f"{head} :- {body}.", comment=f"rule {rule.id}")


def _conditions(when: Condition) -> list[str]:
    goals = ["service(S)"]
    if when.kind:
        goals.append(f"kind(S, {atom(when.kind)})")
    if when.kind_in:
        goals += ["kind(S, K)", f"memberchk(K, [{', '.join(atom(k) for k in when.kind_in)}])"]
    if when.has:
        goals.append(HAS[when.has])
    if when.fact:
        goals.append(f"fact(S, {atom(when.fact)})")
    if when.cardinality:
        goals += ["uses(S, A)", f"association(A, _, _, _, {when.cardinality})"]
    if when.parent_of_composition is True:
        goals += ["acts_on(S, E)", "once(association(_, composition, E, _, _))"]
    elif when.parent_of_composition is False:
        goals += ["acts_on(S, E)", "\\+ association(_, composition, E, _, _)"]
    return goals


def _outcomes(then: Outcome, rid: str) -> list[tuple[str, str]]:
    heads = [("component/3", f"component(S, {atom(c)}, {rid})") for c in then.components]
    if then.error_status is not None:
        heads.append(("error_status/3", f"error_status(S, {then.error_status}, {rid})"))
    for field in ("route", "route_param", "query_params", "persistence_target"):
        value = getattr(then, field)
        if value is not None:
            heads.append((f"{field}/3", f"{field}(S, {atom(value)}, {rid})"))
    heads += [
        ("response_includes/3", f"response_includes(S, {atom(x)}, {rid})")
        for x in then.response_includes
    ]
    return heads
